### PR TITLE
Transmissives

### PR DESCRIPTION
**Pull request by Lachei**
Adds transmissive materials for rendering.
Current implementation supports rough transmission, meaning that for rough transmissive materials the ray is scattered instead of perfectly transmitted into the medium.
Implementation does not keep track of current density of the object but assumes to always have a air/object intersection and uses a given ior number for altering the transmitted ray. This is done, as for obj scenes only the ior is given and no optical density.
For the future to get more towards physically based tracing this should be converted to optical density and then being kept track of in the ray tracing.

Further this PR solves an error that occured on my system with newer assimp when trying to parse material color. This bugfix is done by exchanging the read method to the array read version in vsgXchange::assimp implementation. This version is the more stable one and should work bugfree for all versions of assimp.

For an example refractive scene see https://casual-effects.com/data/ the Cornell box set with a cornell box with a glass ball.

### CODE REVIEW

**Review by KnightTec — CHANGES_REQUESTED** [review]

**Comment by KnightTec** [comment]
@Lachei I created a small PR (#34) into this branch that incorporates my comments.

**Comment by Lachei** [comment]
Your change requests are all good. Will merge your updated branch when decided over naming convention.

**Comment by Lachei** [comment]
Was merged in #34 . Closing this as all changes are already in master.

**Comment by KnightTec** [comment]
> Was merged in #34 . Closing this as all changes are already in master.

@Lachei How are the changes from this PR already on master? From what I can see, the last commit to master has been 28 days ago.

**Review by KnightTec — APPROVED** [review]

**Comment by Lachei** [comment]
Your are of course right. I somehow thought merging #34 would be automatically merged into master...

**Pull request merged**
