### PR TITLE
Codeseparation

### PR DESCRIPTION
**Pull request by Lachei**
Separates non clear render pass creation and denoiser adding to their own util files located in a new folder in source/util .

Maybe the namespace should be changed to start with lowercase. @KnightTec what do you think. If we use lowercase for namespaces we would be consistend with vsg and we would have a distinction with classes.

Should be merged after #32.

### CODE REVIEW

**Comment by KnightTec** [comment]
> Separates non clear render pass creation and denoiser adding to their own util files located in a new folder in source/util .
> 
> Maybe the namespace should be changed to start with lowercase. @KnightTec what do you think. If we use lowercase for namespaces we would be consistend with vsg and we would have a distinction with classes.
> 
> Should be merged after #32.

I think lowercase namespaces are good. But why do we need multiple custom namespaces? Wouldn't a single namespace (maybe `vkpbrt`) suffice?

**Comment by Lachei** [comment]
True, will change before review. `vkpbrt` is a good choice i think.

**Comment by KnightTec** [comment]
@Lachei are you still planning to make any changes to this PR? Otherwise it would be good if we could merge this PR before #36 to avoid too many conflicts.

**Comment by Lachei** [comment]
Sorry, had a lot to do on another project and totally forgot about this pr...

**Review by KnightTec — APPROVED** [review]

**Pull request merged**
