### PR TITLE
Josef

### PR DESCRIPTION
**Pull request by Lachei**
1. Added shader compilation while program is running via vsgs ShaderCompiler.
2. Raygen shader now is adopted according to the illumination buffer used for the pbrt pipeline. Also the pipeline now only uses image bindings when they are used by Gbuffer, IlluminationBuffer or Accumulation buffer.
3. Illumination buffer reacts according to denoising type.

@yuphin Pls test if the project compiles on windows.

### CODE REVIEW

**Comment by yuphin** [comment]
Currently, it compiles fine but while launching I'm getting 
```
Warning: Program failed to link.
glslang info log:
ERROR: Linking ray-generation stage: Missing entry point: Each stage requires one entry point
glslang debug info log:
--------
Calling DestroyWindow(_window);
Error: vsg::ShaderStage::_createReflectData(...) failed to create SpvReflectResult. VkResult = 9
```
for the raygen shader(In release mode)

**Comment by Lachei** [comment]
Looks like the program cannot find the raygen.rgen shader. The line `glslang debug info log:` should be followed by the shader code, but there is nothing...
Does it work fine in debug?
Is in the release build folder in the shaders folder the raygen.rgen shader?

**Comment by yuphin** [comment]
Apparently the problem was in the 
```
std::ifstream fin(foundFile, std::ios::ate);
```
line in the `ShaderCompiler::readShaderSource(const Path& filename, const Paths& paths)` function. Basically it doesn't handle Windows newlines (this function is called during shader includes, see the latest commit) for some reason. The resulting code is shorter and hopefully more general but I'm not sure if it's the optimal solution since I directly changed the VSG library code.
I also checked out the latest VSG repo and this part of the code is still there, so I wonder if that part is still buggy in the main repo.

**Comment by Lachei** [comment]
Yep its defeniteley in the way the file is read. I like your version however much more than the vsg version (I was also surprised that not the streaming operators were used...). I opened a bug report with my suggestion as solution to change as little as possible, however i guess your version is definitely better as it supports windows too.
Gonna merge this now.

**Pull request merged**
