### PR TITLE
Vsg subtree

### PR DESCRIPTION
**Pull request by Lachei**
Adds the vsg libraries via `git subtree` command to easily stay up to date with vsg repositories.
Vsg library was moved to `external` folder and the original vsg library structure was taken from the vsg repo. The cmake files were rewritten to support inclusion of the vsg library via cmakes `add_subdirectory` command.
Added all additions that were made in the master branch (raytracing things, fly navigation, inflection...).

Old vsg folder with the vsg library was removed.

### CODE REVIEW

**Comment by Lachei** [comment]
This PR should have high priority and should be merged asap, as otherwise changes to the vsg library have to be made twice!
As i am not familiar with the changes made to vsgXchange for the 3d front importer i would ask @KnightTec to merge the current master branch with this branch to get this branch mergable.

**Comment by KnightTec** [comment]
> This PR should have high priority and should be merged asap, as otherwise changes to the vsg library have to be made twice! As i am not familiar with the changes made to vsgXchange for the 3d front importer i would ask @KnightTec to merge the current master branch with this branch to get this branch mergable.

I merge my changes, however there are still some unresolved conflicts related to code written by @Lachei in the following files:
- CMakeList.txt
- RenderIO.cpp
- VulkanPBRT.cpp

**Comment by Lachei** [comment]
Merged the conflicts and changed a few things for the inclusion of the 3dFrontImporter. Pls check if everything still works properly @KnightTec

**Comment by KnightTec** [comment]
@Lachei I had to add `find_package(nlohmann_json REQUIRED)` to the vsgexchange and main cmake files for it to compile on my system.
However it seems like shader includes do not work properly anymore. The preprocessed raygen shader looks like this:
```
#version 460
#extension GL_EXT_ray_tracing : enable
#extension GL_GOOGLE_include_directive : enable

#pragma import_defines (FINAL_IMAGE, FINAL_IMAGE_HQ, GBUFFER, PREV_GBUFFER, DEMOD_ILLUMINATION, DEMOD_ILLUMINATION_SQUARED, LIGHT_SAMPLE_SURFACE_STRENGTH, LIGHT_SAMPLE_LIGHT_STRENGTH)

// Start of include code : ptStructures.glsl
#ifndef PTSTRUCTURES_H
#define PTSTRUCTURES_H

struct Vertex{
    vec3 pos;
    vec3 normal;
    vec2 uv;
};

struct WaveFrontMaterialPacked
{
  vec4  ambientShininess;
  vec4  diffuseIor;
  vec4  specularDissolve;
  vec4  transmittanceIllum;
  vec4  emissionTextureId;
  uint category_id;
  float pad[3];
};

struct ObjectInstance{
  mat4 objectMat;
  int meshId;
  uint indexStride;
  int pad[2];
};

struct WaveFrontMaterial
{
  vec3  ambient;
  vec3  diffuse;
  vec3  specular;
  vec3  transmittance;
  vec3  emission;
  float shininess;
  float ior;       // index of refraction
  float dissolve;  // 1 == opaque; 0 == fully transparent
  int   illum;     // illumination model (see http://www.fileformat.info/format/material/)
  float alphaCutoff;
  uint category_id;
};

// Light source types(lst)
const uint lst_undefined = 0;
const uint lst_directional = 1;
const uint lst_point = 2;
const uint lst_spot = 3;
const uint lst_ambient = 4;
const uint lst_area = 5;

// a light is generally defined as a plane with 3 verts, a light type, a direction, strength, angle and radius
// with this emissive planes, point lights with varying radii, cone lights and directional lights can be simulated
struct Light{
    vec4 v0Type;
    vec4 v1Strength;
    vec4 v2Angle;
    vec4 dirAngle2;
    vec4 colAmbient;
    vec4 colDiffuse;
    vec4 colSpecular;
    vec4 strengths; //contains in w the inclusive strength of all lights
};

// Encapsulate the various inputs used by the various functions in the shading equation
// We store values in this struct to simplify the integration of alternative implementations
// of the shading terms, outlined in the Readme.MD Appendix.
struct SurfaceInfo{
    float perceptualRoughness;    // roughness value, as authored by the model creator (input to shader)
    float metalness;              // metallic value at the surface
    float alphaRoughness;         // roughness mapped to a more linear change in the roughness (proposed by [2])
    vec3 reflectance0;            // full reflectance color (normal incidence angle)
    vec3 reflectance90;           // reflectance color at grazing angle
    vec3 diffuseColor;            // color contribution from diffuse lighting
    vec3 specularColor;           // color contribution from specular lighting
    vec3 emissiveColor;
    vec3 normal;
    mat3 basis;                   // tbn matrix for converting form object to world space
};

struct PBRInfo
{
    float NdotL;                  // cos angle between normal and light direction
    float NdotV;                  // cos angle between normal and view direction
    float NdotH;                  // cos angle between normal and half vector
    float LdotH;                  // cos angle between light direction and half vector
    float VdotH;                  // cos angle between view direction and half vector
    float VdotL;                  // cos angle between view direction and light direction
    SurfaceInfo s;                // surface information
};

struct RayPayload {
	vec3 position;
    SurfaceInfo si;
    uint category_id;
};

#endif //PTSTRUCTURES_H
```
Only the start of the file and the first include are left. The rest is gone???
Another issue might be that the vsg shader compiler does not have a way to specify include paths anymore.

**Comment by KnightTec** [comment]
> @Lachei I had to add `find_package(nlohmann_json REQUIRED)` to the vsgexchange and main cmake files for it to compile on my system. However it seems like shader includes do not work properly anymore. The preprocessed raygen shader looks like this:
> 
> ```
> #version 460
> #extension GL_EXT_ray_tracing : enable
> #extension GL_GOOGLE_include_directive : enable
> 
> #pragma import_defines (FINAL_IMAGE, FINAL_IMAGE_HQ, GBUFFER, PREV_GBUFFER, DEMOD_ILLUMINATION, DEMOD_ILLUMINATION_SQUARED, LIGHT_SAMPLE_SURFACE_STRENGTH, LIGHT_SAMPLE_LIGHT_STRENGTH)
> 
> // Start of include code : ptStructures.glsl
> #ifndef PTSTRUCTURES_H
> #define PTSTRUCTURES_H
> 
> struct Vertex{
>     vec3 pos;
>     vec3 normal;
>     vec2 uv;
> };
> 
> struct WaveFrontMaterialPacked
> {
>   vec4  ambientShininess;
>   vec4  diffuseIor;
>   vec4  specularDissolve;
>   vec4  transmittanceIllum;
>   vec4  emissionTextureId;
>   uint category_id;
>   float pad[3];
> };
> 
> struct ObjectInstance{
>   mat4 objectMat;
>   int meshId;
>   uint indexStride;
>   int pad[2];
> };
> 
> struct WaveFrontMaterial
> {
>   vec3  ambient;
>   vec3  diffuse;
>   vec3  specular;
>   vec3  transmittance;
>   vec3  emission;
>   float shininess;
>   float ior;       // index of refraction
>   float dissolve;  // 1 == opaque; 0 == fully transparent
>   int   illum;     // illumination model (see http://www.fileformat.info/format/material/)
>   float alphaCutoff;
>   uint category_id;
> };
> 
> // Light source types(lst)
> const uint lst_undefined = 0;
> const uint lst_directional = 1;
> const uint lst_point = 2;
> const uint lst_spot = 3;
> const uint lst_ambient = 4;
> const uint lst_area = 5;
> 
> // a light is generally defined as a plane with 3 verts, a light type, a direction, strength, angle and radius
> // with this emissive planes, point lights with varying radii, cone lights and directional lights can be simulated
> struct Light{
>     vec4 v0Type;
>     vec4 v1Strength;
>     vec4 v2Angle;
>     vec4 dirAngle2;
>     vec4 colAmbient;
>     vec4 colDiffuse;
>     vec4 colSpecular;
>     vec4 strengths; //contains in w the inclusive strength of all lights
> };
> 
> // Encapsulate the various inputs used by the various functions in the shading equation
> // We store values in this struct to simplify the integration of alternative implementations
> // of the shading terms, outlined in the Readme.MD Appendix.
> struct SurfaceInfo{
>     float perceptualRoughness;    // roughness value, as authored by the model creator (input to shader)
>     float metalness;              // metallic value at the surface
>     float alphaRoughness;         // roughness mapped to a more linear change in the roughness (proposed by [2])
>     vec3 reflectance0;            // full reflectance color (normal incidence angle)
>     vec3 reflectance90;           // reflectance color at grazing angle
>     vec3 diffuseColor;            // color contribution from diffuse lighting
>     vec3 specularColor;           // color contribution from specular lighting
>     vec3 emissiveColor;
>     vec3 normal;
>     mat3 basis;                   // tbn matrix for converting form object to world space
> };
> 
> struct PBRInfo
> {
>     float NdotL;                  // cos angle between normal and light direction
>     float NdotV;                  // cos angle between normal and view direction
>     float NdotH;                  // cos angle between normal and half vector
>     float LdotH;                  // cos angle between light direction and half vector
>     float VdotH;                  // cos angle between view direction and half vector
>     float VdotL;                  // cos angle between view direction and light direction
>     SurfaceInfo s;                // surface information
> };
> 
> struct RayPayload {
> 	vec3 position;
>     SurfaceInfo si;
>     uint category_id;
> };
> 
> #endif //PTSTRUCTURES_H
> ```
> 
> Only the start of the file and the first include are left. The rest is gone??? Another issue might be that the vsg shader compiler does not have a way to specify include paths anymore.

Fixed it. The problem was related to `std::string::insert`.

**Comment by KnightTec** [comment]
> Merged the conflicts and changed a few things for the inclusion of the 3dFrontImporter. Pls check if everything still works properly @KnightTec

3D-FRONT import works properly now, even better than before. Seems like most of the weird issues I previously had during the importer implementation were caused by VSG and not Assimp.

**Review by KnightTec — APPROVED** [review]

**Comment by KnightTec** [comment]
> This definitely shouldn't change the behavior. Can you try out the following code if it works correctly:
> 
> ```
>     std::string a = "hello";
>     std::string b = "ciau";
>     int p = 4;
>     a.insert(p, b);
>     p += b.size();
>     std::cout << a << p << std::endl;
> ```
> 
> For me the result is `hellciauo4`.

This works correctly for me as well.

**Comment by Lachei** [comment]
> This works correctly for me as well.

Have you looked into detail what is going wrong when vsg is inserting the includes include by include?

**Comment by KnightTec** [comment]
> This looks like in the msvc string implementation either the string is inserted including the null terminator, or the insertion is simply overwriting the string from the place it should be inserted to. In either case this is not the correct behavior and we should report if this bug exists.

Unbenannt
Also interesting that `strlen()` and `string::size() ` give me different results in the vsg parsing code.

**Comment by Lachei** [comment]
Can you check if there might be an included file with a null character somewhere inside it which causes the deviation?

**Comment by KnightTec** [comment]
> Can you check if there might be an included file with a null character somewhere inside it which causes the deviation?

Just checked it. There are indeed a bunch of null characters at the end of the string. Thats propably the cause of the problem.

**Comment by Lachei** [comment]
> Just checked it. There are indeed a bunch of null characters at the end of the string. Thats propably the cause of the problem.

Then we have to delete those and should reset the vsg code to the original.

**Comment by KnightTec** [comment]
> > Just checked it. There are indeed a bunch of null characters at the end of the string. Thats propably the cause of the problem.
> 
> Then we have to delete those and should reset the vsg code to the original.

Done.

**Comment by Lachei** [comment]
https://github.com/Lachei/VulkanPBRT/pull/17/commits/3d275bb4cd3c371f3a73dfe8bf5cdef7b641a32e This is not what i meant.
The code in vsg seems to be correct. The shader files loaded should not have any null characters inside them. Pls revert all changes made to the ShaderModule.cpp.
I meant we have to erase the null characters in the shader files.

**Comment by KnightTec** [comment]
> [3d275bb](https://github.com/Lachei/VulkanPBRT/commit/3d275bb4cd3c371f3a73dfe8bf5cdef7b641a32e) This is not what i meant. The code in vsg seems to be correct. The shader files loaded should not have any null characters inside them. Pls revert all changes made to the ShaderModule.cpp. I meant we have to erase the null characters in the shader files.

How do we ensure that we never have null chars in shader files?

**Comment by KnightTec** [comment]
> [3d275bb](https://github.com/Lachei/VulkanPBRT/commit/3d275bb4cd3c371f3a73dfe8bf5cdef7b641a32e) This is not what i meant. The code in vsg seems to be correct. The shader files loaded should not have any null characters inside them. Pls revert all changes made to the ShaderModule.cpp. I meant we have to erase the null characters in the shader files.

There are no null chars at the end of the shader:
Unbenannt
That means that they come from vsg code.

**Comment by KnightTec** [comment]
This is how vsg reads the shader file:
```
std::string source;
std::ifstream fin(found_filename, std::ios::ate);
size_t fileSize = fin.tellg();
source.resize(fileSize);
fin.seekg(0);
fin.read(reinterpret_cast<char*>(source.data()), fileSize);
fin.close();
```
Under linux the files size is equal to the length of the string. However under windows line endings are two characters ("\r\n") long. But in the string we get, the line endings are always just on character ("\n").  That means that the file size on windows is always `number_of_lines - 1` larger than the string size. Since vsg reads a string of `length=file_size`, we get exactly `number_of_lines - 1` additional null chars at the end.

**Comment by Lachei** [comment]
Very nice debugging!
I am going to mention this bug in the vsg library. We will wait for the solution they come up with (this should be resolved in about 24 hours)
I think the best solution is to simply add the bit for opening it in binary mode, as mentioned in https://stackoverflow.com/a/15691006.

**Comment by Lachei** [comment]
@KnightTec can you try if the bug is gone when we simply add the binary flag to the ifstream?

**Comment by KnightTec** [comment]
> @KnightTec can you try if the bug is gone when we simply add the binary flag to the ifstream?

Yes, it works with the binary flag.

**Comment by Lachei** [comment]
Perfect, gonna merge with master and close.
Also, i will mention in the vsg library as a good and working solution.

**Comment by Lachei** [comment]
@KnightTec your version is not compilable under Linux. The flags have to be or'ed on Linux. Pls verify that it compiles...

**Comment by KnightTec** [comment]
> @KnightTec your version is not compilable under Linux. The flags have to be or'ed on Linux. Pls verify that it compiles...

Actually it has to be or'ed on Windows as well. I had it implemented and tested correctly on another branch, but messed it up on this branch in a hurry.

I think [pre-commit hooks](https://github.com/pocc/pre-commit-hooks) would be a nice way to avoid small mistakes like this and safe us some time. And we would always have nicely formatted code 😃.

**Pull request merged**
