### PR TITLE
External exr buffer images

### PR DESCRIPTION
**Pull request by Lachei**
Adds the ability to use external .exr images and denoises them as well as adds the ability to export renderings.
The following command line arguments have been added:
`--dephts` :  filename format of external depth images
`--exportDepth`: filename format of exported depth images
`--positions`: filename format of external positions (only depths or positions should be specified. If both, depth is taken)
`--exportPosition`: filename format of exported position images
`--normals`: filename format of external normal images
`--exportNormal`: filename format of exported normal images
`--albedos`: filename format of external albedo images
`--exportAlbedo`: filename format of exported albedo images
`--materials`: filename format of external material images (currently not used)
`--exportMaterial`: filename format of exported material images (are exported!)
`--matrices`: filename format of external camera matrices corresponding to external dataset (currently only dataset of BMFR matrices can be read)
`--exportMatrices`: filename format of exported camera matrices (currently not used, have not yet decided on file format to store matrices)
Format means that the filename can be a c-style format string with a single `%d` where the frame number will be inserted (eg: `"folder/depth_%d.exr"`).

Further an option for high quality path tracing has been added as the currently used rgba8 buffer (8 bit per channel) fails to get rid of all noise.
`-hq` or `--highqual` enables the 4 component float resulting image.

For review check compilation, your scenes and high quality mode (and maybe export).

### CODE REVIEW

**Review by KnightTec — CHANGES_REQUESTED** [review]
Would it make sense to remove the -hq option and just use the high quality buffer by default? I cannot imagine any scenario where we would want to prevent the lighting from converging due to low precision.

**Comment by Lachei** [comment]
Yes it would! 
Pushed a commit with the change

**Comment by KnightTec** [comment]
Rendering works flawlessly, also with the 3D-FRONT scenes.

However when checking export options I noticed the following things:
- when all export options are used at once, position and illumination buffers are not exported
- when only exportIllumination is used, the exported images contain the final image instead of just the illumination
- exported depths are all zero

**Comment by Lachei** [comment]
> when only exportIllumination is used, the exported images contain the final image instead of just the illumination

Currently illumination is meant to be the final image. The illumination you refer to is i guess the illumination with demodulated first hit albedo, which currently can not be exported...

I will check the faulty exported images tomorrow. However last time i checked the PR on my machine the export worked...

**Comment by Lachei** [comment]
Can not confirm the problems with the export on my machine (Linux Ubuntu).

Positions doesn't work yet as the matrix exporting was not yet implemented (did not finalize the matrix layout for exporting). This will be added on friday.

With what program did you look at the depth image? The depth is stored in the Y component of the image, not all viewers support view of this channel...

**Comment by KnightTec** [comment]
> With what program did you look at the depth image? The depth is stored in the Y component of the image, not all viewers support view of this channel...

Renderdoc

**Comment by Lachei** [comment]
> Renderdoc

Ah ok. Render doc does not load the y channel if available. If you try eg. Blender, you can see the depth(you might have to decrease the lighting of the image to get a good view of it).
Changes are now made to the Gbuffer exporter to properly export only some of the gbuffer as well as the depth images.

**Review by KnightTec — APPROVED** [review]

**Pull request merged**
